"use client";

import MainLayout from "@/components/layout/MainLayout";
import ChildEditorModal from "@/components/children/ChildEditorModal";
import { useAuth } from "@/components/providers/AuthProvider";
import { deriveFamiliesFromChildren } from "@/lib/family-derived";
import { emptyForm, type ChildFormState, type ChildRecord } from "@/lib/children";
import { Archive, Baby, CalendarClock, Download, FileWarning, HeartPulse, Home, LoaderCircle, MoreHorizontal, Pencil, Plus, Search, UsersRound, X } from "lucide-react";
import Link from "next/link";
import { FormEvent, useCallback, useEffect, useMemo, useState, type ReactNode } from "react";

const HERO_KIDS = "/children-center-kids.jpg";
const sites = [
  ["Halcom",14,"from-[#f5e7da] to-[#fff7ef]","text-[#b95d3b]"],
  ["Cornejo",14,"from-[#e9eee2] to-[#f7faf3]","text-[#6a795d]"],
  ["Lara",14,"from-[#f8e2ad] to-[#fff7df]","text-[#d28a07]"],
  ["Division",17,"from-[#f1cfc0] to-[#fff1e9]","text-[#b95d3b]"],
  ["21st",14,"from-[#e6ece2] to-[#f7faf4]","text-[#6a795d]"],
  ["Tehachapi",14,"from-[#f6e4d8] to-[#fff7f1]","text-[#b95d3b]"],
] as const;
const keyFor = (v:string) => /halcom/i.test(v)?"Halcom":/33rd|cornejo/i.test(v)?"Cornejo":/42nd|lara/i.test(v)?"Lara":/division|school age/i.test(v)?"Division":/21st|cathers/i.test(v)?"21st":"Tehachapi";
const nameOf = (c:ChildRecord) => `${c.firstName} ${c.lastName}`.trim();
const initials = (c:ChildRecord) => `${c.firstName?.[0]??""}${c.lastName?.[0]??""}`.toUpperCase();
const toForm = (c:ChildRecord):ChildFormState => ({firstName:c.firstName,lastName:c.lastName,age:c.age,dateOfBirth:c.dateOfBirth,ageGroup:c.ageGroup,location:c.location,classroom:c.classroom,primaryGuardian:c.primaryGuardian,secondaryGuardian:c.secondaryGuardian??"",phone:c.phone,familyName:c.familyName??"",guardianEmail:c.guardianEmail??"",subsidy:c.subsidy,weeklySchedule:c.weeklySchedule,transportation:c.transportation,allergies:c.allergies,medicalNotes:c.medicalNotes,licensingStatus:c.licensingStatus,missingDocuments:c.missingDocuments.join(", "),enrollmentStatus:c.enrollmentStatus,attendanceToday:c.attendanceToday});

export default function ChildrenCenterPage(){
  const {session,isEmployee}=useAuth();
  const canManage=!isEmployee;
  const [children,setChildren]=useState<ChildRecord[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
  const [error,setError]=useState(""),[notice,setNotice]=useState(""),[search,setSearch]=useState(""),[siteFilter,setSiteFilter]=useState("All Locations"),[ageFilter,setAgeFilter]=useState("All Children");
  const [editing,setEditing]=useState<ChildRecord|null>(null),[selected,setSelected]=useState<ChildRecord|null>(null),[form,setForm]=useState<ChildFormState>({...emptyForm}),[familyMode,setFamilyMode]=useState<"existing"|"new">("new"),[selectedFamilyId,setSelectedFamilyId]=useState<number|"">("");
  const request=useCallback(async(method:"GET"|"POST",body?:Record<string,unknown>)=>{if(!session?.access_token)throw new Error("Your staff session is not ready yet.");const r=await fetch("/api/children",{method,headers:{Authorization:`Bearer ${session.access_token}`,...(body?{"Content-Type":"application/json"}:{})},body:body?JSON.stringify(body):undefined,cache:"no-store"});const raw=await r.text();let p:any={};try{p=raw?JSON.parse(raw):{}}catch{p={error:raw}}if(!r.ok)throw new Error(p.error||"The child database request failed.");return p;},[session?.access_token]);
  const load=useCallback(async()=>{if(!session?.access_token)return;setLoading(true);try{const p=await request("GET");setChildren(Array.isArray(p.children)?p.children:[]);setError("")}catch(e){setError(e instanceof Error?e.message:"Could not load child records.")}finally{setLoading(false)}},[request,session?.access_token]);
  useEffect(()=>{void load()},[load]);
  const live=children.filter(c=>c.enrollmentStatus!=="Archived"), active=children.filter(c=>c.enrollmentStatus==="Active"), pending=children.filter(c=>c.enrollmentStatus==="Pending");
  const families=useMemo(()=>deriveFamiliesFromChildren(live),[children]);
  const fileAlerts=live.filter(c=>c.licensingStatus==="Missing Documents").length, healthAlerts=live.filter(c=>!/^none reported$/i.test(c.allergies||"None reported")).length,totalCap=sites.reduce((n,s)=>n+s[1],0),open=Math.max(0,totalCap-active.length),pct=Math.min(100,Math.round(active.length/totalCap*100));
  const siteRows=sites.map(s=>{const enrolled=active.filter(c=>keyFor(c.location)===s[0]).length;return {key:s[0],capacity:s[1],tone:s[2],icon:s[3],enrolled,open:Math.max(0,s[1]-enrolled),pct:Math.min(100,Math.round(enrolled/s[1]*100))}});
  const filtered=live.filter(c=>(!search||`${nameOf(c)} ${c.primaryGuardian} ${c.location} ${c.subsidy}`.toLowerCase().includes(search.toLowerCase()))&&(siteFilter==="All Locations"||keyFor(c.location)===siteFilter)&&(ageFilter==="All Children"||c.ageGroup===ageFilter)).sort((a,b)=>nameOf(a).localeCompare(nameOf(b)));
  const flash=(v:string)=>{setNotice(v);setTimeout(()=>setNotice(""),2600)};
  function openAdd(){setEditing({} as ChildRecord);setForm({...emptyForm});setFamilyMode(families.length?"existing":"new");setSelectedFamilyId("");setError("")}
  function openEdit(c:ChildRecord){setEditing(c);setForm(toForm(c));const f=families.find(x=>c.familyId?x.id===c.familyId:x.primaryGuardian.toLowerCase()===c.primaryGuardian.toLowerCase());setFamilyMode(f?"existing":"new");setSelectedFamilyId(f?.id??"");setSelected(null)}
  function chooseFamily(v:string){if(!v)return setSelectedFamilyId("");const f=families.find(x=>x.id===Number(v));if(!f)return;setSelectedFamilyId(f.id);setForm(x=>({...x,familyName:f.familyName,primaryGuardian:f.primaryGuardian,secondaryGuardian:f.secondaryGuardian,phone:f.phone,guardianEmail:f.email,subsidy:f.subsidy}))}
  async function saveChild(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!canManage)return;if(!form.firstName.trim()||!form.lastName.trim())return setError("Enter the child’s first and last name.");if(!form.primaryGuardian.trim())return setError("Enter at least one parent or guardian.");if(familyMode==="existing"&&selectedFamilyId==="")return setError("Choose an existing family or Create New Family.");const fam=selectedFamilyId===""?undefined:families.find(x=>x.id===selectedFamilyId),missing=form.licensingStatus==="Missing Documents"?form.missingDocuments.split(",").map(x=>x.trim()).filter(Boolean):[];const child:ChildRecord={id:editing?.id||Date.now(),firstName:form.firstName.trim(),lastName:form.lastName.trim(),age:form.age.trim()||"Age not entered",dateOfBirth:form.dateOfBirth,ageGroup:form.ageGroup,location:form.location,classroom:form.classroom.trim()||`${form.ageGroup} Room`,primaryGuardian:fam?.primaryGuardian??form.primaryGuardian.trim(),secondaryGuardian:(fam?.secondaryGuardian??form.secondaryGuardian.trim())||undefined,phone:fam?.phone??form.phone.trim(),familyId:fam?.id??editing?.familyId??Date.now()+1,familyName:fam?.familyName??(form.familyName.trim()||`${form.lastName.trim()} Family`),guardianEmail:(fam?.email??form.guardianEmail.trim())||undefined,subsidy:fam?.subsidy??form.subsidy,weeklySchedule:form.weeklySchedule.trim()||"Schedule not entered",transportation:form.transportation.trim()||"No transportation",allergies:form.allergies.trim()||"None reported",medicalNotes:form.medicalNotes.trim()||"No current medical notes",licensingStatus:form.licensingStatus,missingDocuments:missing,enrollmentStatus:form.enrollmentStatus,attendanceToday:form.attendanceToday};setSaving(true);try{const p=await request("POST",{action:"save",child});setChildren(x=>x.some(i=>i.id===p.child.id)?x.map(i=>i.id===p.child.id?p.child:i):[...x,p.child]);setEditing(null);flash(`${nameOf(p.child)} saved securely.`)}catch(e){setError(e instanceof Error?e.message:"Could not save child.")}finally{setSaving(false)}}
  async function archive(c:ChildRecord){setSaving(true);try{const p=await request("POST",{action:"archive",child:c});setChildren(x=>x.map(i=>i.id===p.child.id?p.child:i));setSelected(null);flash(`${nameOf(c)} archived.`)}catch(e){setError(e instanceof Error?e.message:"Could not archive child.")}finally{setSaving(false)}}
  function exportRoster(){const rows=[["Child","Age","Location","Age Group","Schedule","Pay Source","Status"],...filtered.map(c=>[nameOf(c),c.age,keyFor(c.location),c.ageGroup,c.weeklySchedule,c.subsidy,c.enrollmentStatus])];const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="tcs-child-roster.csv";a.click();URL.revokeObjectURL(a.href)}

  return <MainLayout><div className="mx-auto w-full max-w-[1500px] space-y-3 pb-8 text-[#293423]">
    <section className="relative min-h-[190px] overflow-hidden rounded-b-[28px] border border-[#eadfce] bg-[#fff8ed] shadow-sm">
      <div className="absolute -left-6 -top-12 h-40 w-48 rounded-[45%] bg-[#f5d7c5]/65"/><div className="absolute left-[42%] -top-10 h-28 w-44 rounded-[50%] bg-[#efdcc6]/60"/><div className="absolute right-[27%] -bottom-16 h-44 w-44 rounded-full bg-[#d8ddc8]/65"/>
      <div className="relative z-10 max-w-[62%] px-6 py-5 sm:px-8"><p className="text-sm font-medium uppercase tracking-[.28em] text-[#718164]">The Hub</p><h1 className="mt-1 text-4xl font-black leading-none tracking-[-.045em] sm:text-5xl"><span className="text-[#35452f]">CHILDREN</span> <span className="text-[#b95d3b]">CENTER</span></h1><p className="mt-1 text-lg text-[#30352f]">Enrollment, capacity, and child records in one place.</p><p className="mt-4 font-serif text-base italic text-[#57624f]">Growing children, stronger communities.</p></div>
      <img src={HERO_KIDS} alt="Four smiling children" className="absolute bottom-0 right-[3%] hidden h-[175px] w-auto object-contain lg:block"/>
      <div className="absolute right-5 top-5 hidden rotate-[-6deg] font-serif text-sm italic leading-5 text-[#875d49] xl:block">Kind.<br/>Confident.<br/>Connected.<br/><span className="text-[#65745e]">Brighter Tomorrows</span></div>
    </section>

    {(error||notice)&&<div className={`flex justify-between rounded-xl border px-4 py-2 text-sm font-bold ${error?"border-red-200 bg-red-50 text-red-900":"border-emerald-200 bg-emerald-50 text-emerald-900"}`}><span>{error||notice}</span><button onClick={()=>{setError("");setNotice("")}}><X className="h-4 w-4"/></button></div>}

    <section className="grid gap-2 md:grid-cols-3 xl:grid-cols-6">{siteRows.map(s=><button key={s.key} onClick={()=>setSiteFilter(s.key)} className={`overflow-hidden rounded-xl border border-[#e5dacb] bg-gradient-to-br ${s.tone} text-left shadow-sm transition hover:-translate-y-0.5`}><div className="flex items-center gap-2 border-b border-black/5 px-4 py-3"><Home className={`h-5 w-5 ${s.icon}`}/><strong>{s.key}</strong></div><div className="grid grid-cols-3 divide-x divide-[#e5dacb] p-3 text-center"><Cell n={s.capacity} l="Capacity"/><Cell n={s.enrolled} l="Enrolled"/><Cell n={s.open} l="Open Spots" hot/></div></button>)}</section>

    <section className="grid gap-2 sm:grid-cols-2 lg:grid-cols-5"><MiniStat icon={<UsersRound/>} n={active.length} l="Total Enrolled"/><MiniStat icon={<Baby/>} n={open} l="Open Spots"/><MiniStat icon={<CalendarClock/>} n={pending.length} l="Pending Enrollment"/><MiniStat icon={<UsersRound/>} n={families.length} l="Active Families"/><MiniStat icon={<FileWarning/>} n={fileAlerts} l="Documents Missing"/></section>

    <div className="grid gap-3 xl:grid-cols-[minmax(0,1fr)_330px]">
      <div className="space-y-3">
        <section className="rounded-xl border border-[#e8dfd4] bg-white p-3 shadow-sm"><div className="flex flex-wrap gap-2"><Pill active={ageFilter==="All Children"} onClick={()=>setAgeFilter("All Children")}>All Children ({live.length})</Pill>{["Infant","Toddler","Preschool","School Age"].map(a=><Pill key={a} active={ageFilter===a} onClick={()=>setAgeFilter(a)}>{a} ({live.filter(c=>c.ageGroup===a).length})</Pill>)}</div><div className="mt-3 flex flex-col gap-2 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by name, family, pay source…" className="w-full rounded-lg border border-slate-200 py-2 pl-9 pr-3 text-sm outline-none focus:ring-2 focus:ring-[#a9b49e]"/></label><select value={siteFilter} onChange={e=>setSiteFilter(e.target.value)} className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm font-semibold"><option>All Locations</option>{sites.map(s=><option key={s[0]}>{s[0]}</option>)}</select></div></section>

        <section className="overflow-hidden rounded-xl border border-[#e8dfd4] bg-white shadow-sm">{loading?<div className="flex min-h-56 items-center justify-center gap-2 text-slate-500"><LoaderCircle className="h-5 w-5 animate-spin"/> Loading secured child records…</div>:filtered.length===0?<div className="p-12 text-center"><Baby className="mx-auto h-9 w-9 text-[#718164]"/><h2 className="mt-2 font-black">No children match this view</h2></div>:<div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-[#faf7f1] text-xs text-slate-500"><tr>{["Child","Age","Location","Program / Age Group","Schedule","Pay Source","Status","Actions"].map(h=><th key={h} className="px-4 py-3 font-black">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{filtered.map(c=><tr key={c.id} className="hover:bg-[#fffaf1]"><td className="px-4 py-3"><button onClick={()=>setSelected(c)} className="flex items-center gap-3 font-black"><span className="grid h-9 w-9 place-items-center rounded-full bg-[#e7eee1] text-xs text-[#506447]">{initials(c)}</span>{nameOf(c)}</button></td><td className="px-4 py-3">{c.age}</td><td className="px-4 py-3">{keyFor(c.location)}</td><td className="px-4 py-3">{c.ageGroup}</td><td className="max-w-40 truncate px-4 py-3">{c.weeklySchedule}</td><td className="px-4 py-3">{c.subsidy}</td><td className="px-4 py-3"><span className={`rounded-md px-2 py-1 text-xs font-black ${c.enrollmentStatus==="Active"?"bg-[#dceedd] text-[#315b36]":"bg-amber-100 text-amber-800"}`}>{c.enrollmentStatus}</span></td><td className="px-4 py-3"><div className="flex gap-2"><button onClick={()=>setSelected(c)} className="rounded-lg border border-slate-200 px-3 py-1.5 text-xs font-black">View File</button><button onClick={()=>setSelected(c)} className="rounded-lg border border-slate-200 p-1.5"><MoreHorizontal className="h-4 w-4"/></button></div></td></tr>)}</tbody></table></div>}</section>

        <section className="flex flex-wrap gap-3">{canManage&&<button onClick={openAdd} className="inline-flex items-center gap-2 rounded-xl bg-[#445b37] px-5 py-3 text-sm font-black text-white"><Plus className="h-4 w-4"/> Add Child</button>}<Link href="/enrollment-pipeline" className="inline-flex items-center gap-2 rounded-xl bg-[#b95d3b] px-5 py-3 text-sm font-black text-white"><FileWarning className="h-4 w-4"/> Start Enrollment</Link><Link href="/child-schedules" className="inline-flex items-center gap-2 rounded-xl border border-[#e6dfd4] bg-[#fffaf2] px-5 py-3 text-sm font-black"><CalendarClock className="h-4 w-4"/> Child Schedules</Link><button onClick={exportRoster} className="inline-flex items-center gap-2 rounded-xl border border-[#e6dfd4] bg-[#fffaf2] px-5 py-3 text-sm font-black"><Download className="h-4 w-4"/> Export Roster</button></section>
      </div>

      <aside className="space-y-3"><section className="rounded-xl border border-[#e7dfd3] bg-[#fffdf8] p-4 shadow-sm"><h2 className="font-black">Enrollment Snapshot</h2><div className="mt-4 flex items-center gap-4"><div className="grid h-32 w-32 place-items-center rounded-full" style={{background:`conic-gradient(#5d7557 ${pct}%, #f1d2a5 0)`}}><div className="grid h-[86px] w-[86px] place-items-center rounded-full bg-[#fffdf8] text-center"><div><p className="text-2xl font-black">{active.length}</p><p className="text-[10px] font-semibold">Enrolled<br/>({pct}% capacity)</p></div></div></div><div className="space-y-2 text-sm"><p><i className="mr-2 inline-block h-3 w-3 rounded-full bg-[#5d7557]"/>Enrolled <strong>{active.length}</strong></p><p><i className="mr-2 inline-block h-3 w-3 rounded-full bg-[#f1d2a5]"/>Open Spots <strong>{open}</strong></p><p className="pt-2 text-xs text-slate-500">Licensed Capacity</p><p className="text-lg font-black">{totalCap}</p></div></div></section>
      <section className="rounded-xl border border-[#e7dfd3] bg-[#fffdf8] p-4 shadow-sm"><h2 className="font-black">Capacity by Location</h2><div className="mt-3 space-y-3">{siteRows.map(s=><div key={s.key} className="grid grid-cols-[74px_1fr_48px] items-center gap-2 text-xs"><span className="font-semibold">{s.key}</span><div className="h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-[#718164]" style={{width:`${s.pct}%`}}/></div><span className="text-right font-black">{s.enrolled}/{s.capacity}</span></div>)}</div><p className="mt-6 text-center font-serif italic text-[#80523b]">More children.<br/>Brighter communities.</p></section>
      <section className="rounded-xl border border-[#e7dfd3] bg-[#fff8ed] p-4 shadow-sm"><h2 className="font-black">Upcoming Actions</h2><div className="mt-3 space-y-3"><Action icon={<FileWarning/>} n={fileAlerts} label="Missing Child Files"/><Action icon={<CalendarClock/>} n={pending.length} label="Pending Enrollments"/><Action icon={<HeartPulse/>} n={healthAlerts} label="Health Alerts"/></div></section><section className="rounded-xl border border-[#e7dfd3] bg-[#fffaf2] p-5 text-center shadow-sm"><p className="font-serif text-lg italic text-[#506047]">“Every child belongs.<br/>Every family matters.”</p><p className="mt-2 text-xs font-black uppercase tracking-wider text-[#8a6652]">— The Hub</p></section></aside>
    </div>

    {editing&&<ChildEditorModal title={editing.id?`Edit ${nameOf(editing)}`:"Add Child"} form={form} setForm={setForm} families={families} familyMode={familyMode} setFamilyMode={setFamilyMode} selectedFamilyId={selectedFamilyId} chooseFamily={chooseFamily} saving={saving} onClose={()=>setEditing(null)} onSubmit={saveChild}/>} 
    {selected&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/55 p-4"><button className="absolute inset-0" onClick={()=>setSelected(null)} aria-label="Close"/><section className="relative z-10 w-full max-w-2xl rounded-3xl bg-[#fffdf9] p-6 shadow-2xl"><div className="flex justify-between"><div><p className="text-xs font-black uppercase tracking-wider text-[#718164]">Child File</p><h2 className="text-2xl font-black">{nameOf(selected)}</h2><p className="text-sm text-slate-500">{selected.age} • {keyFor(selected.location)} • {selected.ageGroup}</p></div><button onClick={()=>setSelected(null)}><X/></button></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Detail l="Parent / Guardian" v={selected.primaryGuardian}/><Detail l="Phone" v={selected.phone}/><Detail l="Schedule" v={selected.weeklySchedule}/><Detail l="Pay Source" v={selected.subsidy}/><Detail l="Transportation" v={selected.transportation}/><Detail l="File Status" v={selected.licensingStatus}/><Detail l="Allergies / Alerts" v={selected.allergies}/><Detail l="Support Notes" v={selected.medicalNotes}/></div>{canManage&&<div className="mt-5 flex justify-end gap-2"><button onClick={()=>openEdit(selected)} className="inline-flex items-center gap-2 rounded-xl bg-[#445b37] px-4 py-2.5 text-sm font-black text-white"><Pencil className="h-4 w-4"/> Edit File</button><button onClick={()=>void archive(selected)} className="inline-flex items-center gap-2 rounded-xl border border-slate-300 px-4 py-2.5 text-sm font-black"><Archive className="h-4 w-4"/> Archive</button></div>}</section></div>}
  </div></MainLayout>
}
function Cell({n,l,hot=false}:{n:number;l:string;hot?:boolean}){return <div><p className={`text-xl font-black ${hot?"text-[#b95d3b]":""}`}>{n}</p><p className="text-[9px] text-slate-500">{l}</p></div>}
function MiniStat({icon,n,l}:{icon:ReactNode;n:number;l:string}){return <div className="flex items-center gap-3 rounded-xl border border-[#e8dfd4] bg-white px-4 py-3 shadow-sm"><span className="text-[#718164]">{icon}</span><div><p className="text-2xl font-black leading-none">{n}</p><p className="mt-1 text-xs font-semibold text-slate-500">{l}</p></div></div>}
function Pill({active,onClick,children}:{active:boolean;onClick:()=>void;children:ReactNode}){return <button onClick={onClick} className={`rounded-lg px-3 py-2 text-xs font-black ${active?"bg-[#506447] text-white":"bg-[#f4f2ed] text-slate-600"}`}>{children}</button>}
function Action({icon,n,label}:{icon:ReactNode;n:number;label:string}){return <div className="flex items-center gap-3 rounded-lg bg-white px-3 py-2"><span className="text-[#b95d3b]">{icon}</span><p className="text-sm"><strong>{n}</strong> {label}</p></div>}
function Detail({l,v}:{l:string;v:string}){return <div className="rounded-xl bg-[#f7f4ee] p-3"><p className="text-[10px] font-black uppercase tracking-wider text-slate-400">{l}</p><p className="mt-1 text-sm font-bold text-slate-800">{v||"Not entered"}</p></div>}
